[package]
name = "los_arch_aarch64"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
los_hal = { path = "../../lib/hal" }
los_types = { path = "../../lib/types" }
log = "0.4"
aarch64-cpu = { workspace = true }
linked_list_allocator = "0.10"
